### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by sploitable868** [databat-io/sonar#12]
Good day, i'm new to resin.io / balena, this is the first time trying something like this on the pi 3b+. I managed to push the code to my balena acc, the build finished but nothing happens after... i was thinking to access the interface would be pi ipadd:8000 but nothing, port 80 says bad gateway

11.12.18 20:49:24 (-0400)  main  109 static files copied to '/usr/src/app/staticfiles', 151 post-processed.
11.12.18 20:49:24 (-0400)  main  Attaching hci0...
11.12.18 20:49:24 (-0400)  main  bcm43xx_init
11.12.18 20:49:24 (-0400)  main  Failed to write reset command
11.12.18 20:49:24 (-0400)  main  Can't initialize device: Success
11.12.18 20:49:24 (-0400)  main  Bring hci0 up...
11.12.18 20:49:24 (-0400)  main  Scan for devices...
11.12.18 20:49:40 (-0400)  main  Inquiry failed: Connection timed out
11.12.18 20:49:40 (-0400)  main  Initialization failed.
11.12.18 20:49:40 (-0400)  main  Soft error counter: 1/3
11.12.18 20:50:06 (-0400)  main  Attaching hci0...
11.12.18 20:50:06 (-0400)  main  bcm43xx_init
11.12.18 20:50:06 (-0400)  main  Failed to write reset command
11.12.18 20:50:06 (-0400)  main  Can't initialize device: Success
11.12.18 20:50:06 (-0400)  main  Bring hci0 up...
11.12.18 20:50:06 (-0400)  main  Scan for devices...
11.12.18 20:50:22 (-0400)  main  Inquiry failed: Connection timed out
11.12.18 20:50:22 (-0400)  main  Initialization failed.
11.12.18 20:50:22 (-0400)  main  Soft error counter: 2/3
11.12.18 20:50:42 (-0400)  main  Attaching hci0...
11.12.18 20:50:42 (-0400)  main  bcm43xx_init
11.12.18 20:50:42 (-0400)  main  Failed to write reset command
11.12.18 20:50:42 (-0400)  main  Can't initialize device: Success
11.12.18 20:50:42 (-0400)  main  Bring hci0 up...
11.12.18 20:50:42 (-0400)  main  Scan for devices...
11.12.18 20:50:58 (-0400)  main  Inquiry failed: Connection timed out
11.12.18 20:50:58 (-0400)  main  Initialization failed.
11.12.18 20:50:58 (-0400)  main  Soft error counter: 3/3
11.12.18 20:51:47 (-0400)  main  Hard error counter: 1/5
11.12.18 20:51:47 (-0400)  main  All tests failed. Taking hard action in 249 seconds.

**Comment by vpetersson** [comment]
I have not tested this on the Raspberry Pi 3 Model B+ actually. Only  on the Rasperry Pi 3 Model B. Since the B+ uses a different Bluetooth chipset, it's possible that the code will require an update.

**Comment by sploitable868** [comment]
Hey, thanks much for the quick reply, i was wondering that aswell.. flashed it twice same results too. I am very eager to try this out but i only have pi zero w and 3b+...

How long you might take to get this modified for 3b+?

**Comment by vpetersson** [comment]
No clue. This is a side project that I hacked on so it's not top of my priority list unfortunately. That said, I'd be happy to accept code contributions.

**Comment by sploitable868** [comment]
lol ok i understand, seems to me its better i buy a 3b instead of waiting for code up date.. before i do, do you have any running i can get to access the web interface and check it out before buying a 3b?

**Comment by vpetersson** [comment]
@sploitable868  - I found the root cause for the "Bad Request (400)" issue. Turns out it was simply the fact that when Resin renamed themselves to Balena, they also renamed the domain on which the devices are exposed. I just had to add this to the whitelist.
