### ISSUE TITLE
Errors in the balenaCloud log

### ISSUE THREAD

**Issue by nmoustgaard** [databat-io/sonar#15]
Hi,

I'm seeing these errors in the Balena Cloud. Any suggestions what to do from here?
![Screenshot 2019-03-18 at 10 23 11](https://user-images.githubusercontent.com/48671986/54520010-fc029e80-4967-11e9-932d-35b40d3f1d50.png)

**Comment by vpetersson** [comment]
What hardware are you running on? I have only tested it on the Raspberry Pi 3 Model B (not B+).

It is expected that you will see this periodically, as it has to do with the Bluetooth module, where I had to apply a fair amount of brute-force to get it to play ball. It should however recover.

**Comment by nmoustgaard** [comment]
Thanks for the quick response!

Sorry, I asked my question before reading the other questions previously asked and I saw that one other guy had encountered the same problem together with your response. I ordered a Raspberry Pi 3 Model B (not B+) yesterday and hopefully, I will receive by tomorrow.

Will let you know how that works :-)

**Comment by nmoustgaard** [comment]
Hi again,

I've now received my Raspberry Pi 3 Model B (not B+) and installed the application but I still see the following logs from the balenaCloud. Do you have any ideas on how to fix this?

BR,
![Screenshot 2019-03-22 at 14 32 26](https://user-images.githubusercontent.com/48671986/54826244-ad2e6f00-4caf-11e9-876f-ce3199b7e68f.png)

**Comment by nmoustgaard** [comment]
![Screenshot 2019-03-22 at 14 54 10](https://user-images.githubusercontent.com/48671986/54827538-89205d00-4cb2-11e9-903d-ad77e03f8e27.png)

**Comment by vpetersson** [comment]
@nmoustgaard what happens if you just leave it? I've seen that in the past, but in my experience it recovers.

**Comment by nmoustgaard** [comment]
Hi Viktor. I tried to leave it but it did not change much. I've uploaded the log files here.
[blecounter_empty-field-26.03.19_11_43_01_(+0100).txt](https://github.com/databat-io/sonar/files/3007738/blecounter_empty-field-26.03.19_11_43_01_.%2B0100.txt)

**Comment by vpetersson** [comment]
Sorry - i have not had time to look at this - been swamped with other projects unfortunately.

**Comment by vpetersson** [comment]
@nmoustgaard I've resurrected this project and made a major overhaul to how the Bluetooth interface is brought up. It should be a lot more reliable now. Please take a look if you're still  interested. Closing out the ticket, but feel free to re-open it if the problem persists.
