### ISSUE TITLE
Datepicker selects timestamp

### ISSUE THREAD

**Issue by nmoustgaard** [databat-io/sonar#16]
Hi,

When using the datepicker to select a date, the datepicker automatically adds a timestamp to your selection and you cannot delete it. When click "Go to report" you receive an error due to the number of characters in the field.
![Screenshot 2019-03-18 at 10 26 28](https://user-images.githubusercontent.com/48671986/54520183-6a476100-4968-11e9-8018-e764a7bd8666.png)
![Screenshot 2019-03-18 at 10 26 20](https://user-images.githubusercontent.com/48671986/54520184-6a476100-4968-11e9-99cf-105b54034fa2.png)

**Comment by vpetersson** [comment]
Interesting. Good catch.

**Comment by vpetersson** [comment]
I've reproduced this issue. Will see if i can knock it out shortly.

**Comment by vpetersson** [comment]
@nmoustgaard Strange. I was only able to reproduce this issue on an empty records database. Once the data has been populated, I was no longer able to reproduce it. Is this still an issue? Closing out this issue. Feel free to re-open if you're able to reproduce it.
